### ISSUE TITLE
PhoneGapBuild won't build

### ISSUE THREAD

**Issue by propertylink** [honza889/cordova-plugin-kiosk#74]
Running into this error with phonegap build:
Error - Plugin error (you probably need to remove plugin files from your app): //github.com/hkalina/cordova-plugin-kiosk.git --nohooks=.": Fetching plugin "https://github.com/hkalina/cordova-plugin-kiosk.git" via git clone Using shallow clone Repository "https://github.com/hkalina/cordova-plugin-kiosk.git" checked out to git ref "master" at "05fb38e". Installing "cordova-plugin-kiosk" at "0.2" for android Failed to install 'cordova-plugin-kiosk': Error: Unable to graft xml at selector "/manifest/application/activity[@android:label='@string/activity_name']" from "/var/gimlet/tmp/47199364576660/3624425/www_android/project/AndroidManifest.xml" during config install at ConfigFile_graft_child [as graft_child] (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:120:19) at PlatformMunger_apply_file_munge [as apply_file_munge] (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:86:34) at munge_helper (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:265:14) at PlatformMunger.add_plugin_changes (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:179:12) at /var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/cordova-common/src/PluginManager.js:126:25 at _fulfilled (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/q/q.js:834:54) at self.promiseDispatch.done (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/q/q.js:863:30) at Promise.promise.promiseDispatch (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/q/q.js:796:13) at /var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/q/q.js:857:14 at runSingle (/var/gimlet/tmp/47199364576660/3624425/www_android/project/cordova/node_modules/q/q.js:137:13) Unable to graft xml at selector "/manifest/application/activity[@android:label='@string/activity_name']" from "/var/gimlet/tmp/47199364576660/3624425/www_android/project/AndroidManifest.xml" during config install - You can fix this here

I have tried every combination of plugin installations, with and without adding android platform, etc. I even created a brand new app from scratch and moved my source files. Can't get it to build. Any insights? Sorry if it's something easy I am still a bit new to cordova.

**Comment by kidGodzilla** [comment]
I'm experiencing this as well. Phonegap build pointed me here: http://docs.phonegap.com/phonegap-build/support/failed-builds/#plugin-error

**Comment by propertylink** [comment]
> I'm experiencing this as well. Phonegap build pointed me here: http://docs.phonegap.com/phonegap-build/support/failed-builds/#plugin-error

Let me know what you end up figuring out if you don't mind. I took a look at your project and although different in practice, We seem to be after identical kiosk features - Tablet as a kiosk in a stationary location.

I saw a couple other plugins as well, but couldn't seem to get anything to work. This one seemed to be the most popular / supported, but no dice.
